# Black Duck on GitHub-hosted ephemeral runner
name: blackduck

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      BLACKDUCK_URL: "https://testing.blackduck.synopsys.com"
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      PROJECT: "mvnwebapp1"
      #BRANCH: ${GITHUB_REF##*/}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Black Duck Scan
      uses: blackducksoftware/github-action@v2
      with:
        args: --detect.project.name=$PROJECT --detect.project.version.name="Main" --detect.excluded.detector.types=GRADLE
